/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.unikom.sbd3.tokopakaian;

import id.ac.unikom.sbd3.tokopakaian.dao.PegawaiDAO;
import id.ac.unikom.sbd3.tokopakaian.dao.TransaksiKonsumenDAO;
import id.ac.unikom.sbd3.tokopakaian.dao.TransaksiResellerDAO;
import id.ac.unikom.sbd3.tokopakaian.daoimpl.PegawaiDAOImpl;
import id.ac.unikom.sbd3.tokopakaian.daoimpl.TransaksiKonsumenDAOImpl;
import id.ac.unikom.sbd3.tokopakaian.daoimpl.TransaksiResellerDAOImpl;
import id.ac.unikom.sbd3.tokopakaian.entity.Pegawai;
import id.ac.unikom.sbd3.tokopakaian.entity.TransaksiKonsumen;
import id.ac.unikom.sbd3.tokopakaian.entity.TransaksiReseller;
import id.ac.unikom.sbd3.tokopakaian.tabelmodel.TransaksiKonsumenTM;
import id.ac.unikom.sbd3.tokopakaian.tabelmodel.TransaksiResellerTM;
import id.ac.unikom.sbd3.tokopakaian.utility.DatabaseConnectivity;
import java.io.File;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Iqram
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    private Pegawai pegawai = null;
    ArrayList<TransaksiReseller> arrayTransaksiReseller;
    ArrayList<TransaksiKonsumen> arrayTransaksiKonsumen;
    private TransaksiResellerDAO tr;
    private TransaksiKonsumenDAO tk;
    String hakakses;
    String login;

    java.sql.Connection conn;
    JasperReport jasRep;
    JasperPrint jasPri;
   // Map<String, Object> id = new HashMap<String, Object>();
    Map param = new HashMap();
    JasperDesign jasDes;
    DatabaseConnectivity koneksi = new DatabaseConnectivity();

    public FormUtama() {
        initComponents();
        ButtonGroup grupRadio = new ButtonGroup();
        grupRadio.add(radioAdmin);
        grupRadio.add(radioOperator);
        setAkses();
        refreshData();
    }

    private void setAkses() {
        btnPegawai.setEnabled(false);
        btnLogout.setEnabled(false);
        btnPakaian.setEnabled(false);
        btnReseller.setEnabled(false);
        btnTransKonsumen.setEnabled(false);
        btnTransReseller.setEnabled(false);
        lblLogin.setText("???");
        lblStatus.setText("Belum Login");
    }

    private void getDataTR() {
        tr = new TransaksiResellerDAOImpl();
        arrayTransaksiReseller = tr.getTransaksiReseller();

        TransaksiResellerTM tmtr = new TransaksiResellerTM();
        tmtr.setArrayReseller(arrayTransaksiReseller);

        tableTransReseller.setModel(tmtr);
    }

    private void getDataTR(int keyword) {
        tr = new TransaksiResellerDAOImpl();
        arrayTransaksiReseller = tr.getTransaksiReseller(keyword);

        TransaksiResellerTM tmtr = new TransaksiResellerTM();
        tmtr.setArrayReseller(arrayTransaksiReseller);

        tableTransReseller.setModel(tmtr);
    }

    private void getDataTK() {
        tk = new TransaksiKonsumenDAOImpl();
        arrayTransaksiKonsumen = tk.getTransaksiKonsumen();

        TransaksiKonsumenTM tmtk = new TransaksiKonsumenTM();
        tmtk.setArrayKonsumen(arrayTransaksiKonsumen);

        tableTransKonsumen.setModel(tmtk);
    }

    private void getDataTK(int keyword) {
        tk = new TransaksiKonsumenDAOImpl();
        arrayTransaksiKonsumen = tk.getTransaksiKonsumen(keyword);

        TransaksiKonsumenTM tmtk = new TransaksiKonsumenTM();
        tmtk.setArrayKonsumen(arrayTransaksiKonsumen);

        tableTransKonsumen.setModel(tmtk);
    }

    private void refreshData() {
        getDataTK();
        getDataTR();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldPass = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        radioAdmin = new javax.swing.JRadioButton();
        radioOperator = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnPegawai = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        btnPakaian = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransKonsumen = new javax.swing.JTable();
        lblLogin = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTransReseller = new javax.swing.JTable();
        btnReseller = new javax.swing.JButton();
        btnReportTR = new javax.swing.JButton();
        btnBackupRestore = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnTransReseller = new javax.swing.JButton();
        btnTransKonsumen = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        fieldCariTKonsumen = new javax.swing.JTextField();
        btnCariTkonsumen = new javax.swing.JButton();
        fieldCariTReseller = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnCariTreseller = new javax.swing.JButton();
        btnReportTransaksiKonsumen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Login Sebagai : ");

        jLabel2.setText("Status : ");

        jLabel3.setText("Username : ");

        jLabel4.setText("Password : ");

        fieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPassActionPerformed(evt);
            }
        });

        jLabel5.setText("Akses : ");

        buttonGroup1.add(radioAdmin);
        radioAdmin.setSelected(true);
        radioAdmin.setText("Admin");
        radioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAdminActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioOperator);
        radioOperator.setText("Operator");

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel6.setText("Toko Pakaian Barokah");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("orange juice", 0, 24)); // NOI18N
        jLabel7.setText("Menu");

        btnPegawai.setText("Pegawai");
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setText("Copyright © 2016");

        btnPakaian.setText("Pakaian");
        btnPakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPakaianActionPerformed(evt);
            }
        });

        jLabel9.setText("Tabel Transaksi Konsumen");

        tableTransKonsumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableTransKonsumen);

        jLabel10.setText("Tabel Transaksi Reseller");

        tableTransReseller.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableTransReseller);

        btnReseller.setText("Reseller");
        btnReseller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResellerActionPerformed(evt);
            }
        });

        btnReportTR.setText("Report Trans Reseller");
        btnReportTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportTRActionPerformed(evt);
            }
        });

        btnBackupRestore.setText("Backup & Restore");
        btnBackupRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupRestoreActionPerformed(evt);
            }
        });

        jLabel11.setText("TRANSAKSI");

        btnTransReseller.setText("Reseller");
        btnTransReseller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransResellerActionPerformed(evt);
            }
        });

        btnTransKonsumen.setText("Konsumen");
        btnTransKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransKonsumenActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel12.setText("Cari ID  : ");

        fieldCariTKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCariTKonsumenActionPerformed(evt);
            }
        });

        btnCariTkonsumen.setText("Cari");
        btnCariTkonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariTkonsumenActionPerformed(evt);
            }
        });

        fieldCariTReseller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCariTResellerActionPerformed(evt);
            }
        });

        jLabel13.setText("Cari ID  : ");

        btnCariTreseller.setText("Cari");
        btnCariTreseller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariTresellerActionPerformed(evt);
            }
        });

        btnReportTransaksiKonsumen.setText("Report Trans Konsumen");
        btnReportTransaksiKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportTransaksiKonsumenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(btnPakaian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7))
                            .addComponent(btnReseller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel11))
                            .addComponent(btnTransReseller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTransKonsumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(92, 92, 92)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldCariTKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCariTkonsumen)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnReportTransaksiKonsumen)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(btnBackupRestore)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRefresh)
                                        .addGap(46, 46, 46))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(97, 97, 97)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldCariTReseller, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCariTreseller)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnReportTR)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(248, 248, 248)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioAdmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioOperator))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jLabel6)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(radioAdmin)
                            .addComponent(radioOperator)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(9, 9, 9)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(btnPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReseller, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(24, 24, 24)
                        .addComponent(btnTransReseller, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTransKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(fieldCariTKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCariTkonsumen)
                            .addComponent(btnReportTransaksiKonsumen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(fieldCariTReseller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCariTreseller)
                            .addComponent(btnReportTR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBackupRestore)
                            .addComponent(btnRefresh)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPassActionPerformed

    private void radioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAdminActionPerformed

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        FormPegawai fp = new FormPegawai(null, true);
        fp.setLocationRelativeTo(null);
        fp.setVisible(true);
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = fieldUserName.getText();
        String password = String.valueOf(fieldPass.getPassword());
        String hakAkses;

        if (radioAdmin.isSelected()) {
            hakAkses = radioAdmin.getText();
        } else {
            hakAkses = radioOperator.getText();
        }
        //validasi input data
        if (username.isEmpty() || password.isEmpty() || hakAkses.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi Form Login");
        } else {
            //validasi login
            PegawaiDAO dao = new PegawaiDAOImpl();
            pegawai = dao.login(username, password, hakAkses);
            if (pegawai != null) {
                hakakses = pegawai.getHakAkses();
            }
            // cek hasil login
            if (pegawai != null && hakakses.equalsIgnoreCase("Admin")) {
                btnPegawai.setEnabled(true);
                btnLogout.setEnabled(true);
                btnLogin.setEnabled(false);
                btnPakaian.setEnabled(true);
                btnReseller.setEnabled(true);
                btnTransKonsumen.setEnabled(true);
                btnTransReseller.setEnabled(true);
                lblLogin.setText(pegawai.getNama());
                lblStatus.setText("Admin");
                JOptionPane.showMessageDialog(this,
                        "Login berhasil : " + pegawai.getNama());
            } else if (pegawai != null && hakakses.equalsIgnoreCase("Operator")) {
                btnLogout.setEnabled(true);
                btnLogin.setEnabled(false);
                lblLogin.setText(pegawai.getNama());
                lblStatus.setText("Operator");
                btnReseller.setEnabled(true);
                btnPakaian.setEnabled(true);
                btnTransKonsumen.setEnabled(true);
                btnTransReseller.setEnabled(true);
                JOptionPane.showMessageDialog(this,
                        "Login berhasil : " + pegawai.getNama());
            } else {
                fieldUserName.setText("");
                fieldPass.setText("");
                JOptionPane.showMessageDialog(this,
                        "Login gagal");
            }
            {
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        hakakses = null;
        fieldUserName.setText("");
        fieldPass.setText("");
        btnPegawai.setEnabled(false);
        btnLogout.setEnabled(false);
        btnLogin.setEnabled(true);
        btnPakaian.setEnabled(false);
        btnReseller.setEnabled(false);
        btnTransKonsumen.setEnabled(false);
        btnTransReseller.setEnabled(false);
        lblLogin.setText("???");
        lblStatus.setText("Belum Login");
        JOptionPane.showMessageDialog(this, "Berhasil Logout");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPakaianActionPerformed
        FormPakaian fpn = new FormPakaian(null, true);
        fpn.setLocationRelativeTo(null);
        fpn.setVisible(true);

    }//GEN-LAST:event_btnPakaianActionPerformed

    private void btnResellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResellerActionPerformed
        FormReseller fr = new FormReseller(null, true);
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_btnResellerActionPerformed

    private void btnTransKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransKonsumenActionPerformed
        login = pegawai.getNip();
        FormTransaksiKonsumen ftk = new FormTransaksiKonsumen(null, true, login);
        ftk.setLocationRelativeTo(null);
        ftk.setVisible(true);
    }//GEN-LAST:event_btnTransKonsumenActionPerformed

    private void btnTransResellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransResellerActionPerformed
        login = pegawai.getNip();
        FormTransaksiReseller ftr = new FormTransaksiReseller(null, true, login);
        ftr.setLocationRelativeTo(null);
        ftr.setVisible(true);
    }//GEN-LAST:event_btnTransResellerActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void fieldCariTKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCariTKonsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariTKonsumenActionPerformed

    private void fieldCariTResellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCariTResellerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariTResellerActionPerformed

    private void btnBackupRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupRestoreActionPerformed
        FormBackupRestore fbr = new FormBackupRestore(null, true);
        fbr.setLocationRelativeTo(null);
        fbr.setVisible(true);

    }//GEN-LAST:event_btnBackupRestoreActionPerformed

    private void btnCariTresellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariTresellerActionPerformed
        String cari = fieldCariTReseller.getText();

        // validasi kata kunci
        if (cari != null && !cari.isEmpty()) {
            //proses pencarian
            int keyword = Integer.parseInt(cari);
            getDataTR(keyword);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Data pencarian tidak boleh kosong");
        }
    }//GEN-LAST:event_btnCariTresellerActionPerformed

    private void btnCariTkonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariTkonsumenActionPerformed
        String cari = fieldCariTKonsumen.getText();

        // validasi kata kunci
        if (cari != null && !cari.isEmpty()) {
            //proses pencarian
            int keyword = Integer.parseInt(cari);
            getDataTK(keyword);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Data pencarian tidak boleh kosong");
        }
    }//GEN-LAST:event_btnCariTkonsumenActionPerformed

    private void btnReportTransaksiKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportTransaksiKonsumenActionPerformed

        try {
            //Class.forName("org.postgresql.Driver");
            //conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_perpus", "root", "");
            File report = new File("src\\id\\ac\\unikom\\sbd3\\tokopakaian\\ReportTransaksiKonsumen.jrxml");
            jasDes = JRXmlLoader.load(report);
            param.clear();
            jasRep = JasperCompileManager.compileReport(jasDes);
            jasPri = JasperFillManager.fillReport(jasRep, param, koneksi.getConnection());
            JasperViewer.viewReport(jasPri, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnReportTransaksiKonsumenActionPerformed

    private void btnReportTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportTRActionPerformed
        try {
            //Class.forName("org.mysql.jdbc.Driver");
            //conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_perpus", "root", "");
            File report = new File("src\\id\\ac\\unikom\\sbd3\\tokopakaian\\ReportTransaksiReseller.jrxml");
            jasDes = JRXmlLoader.load(report);
            param.clear();
            jasRep = JasperCompileManager.compileReport(jasDes);
            jasPri = JasperFillManager.fillReport(jasRep, param, koneksi.getConnection());
            JasperViewer.viewReport(jasPri, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnReportTRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormUtama fu = new FormUtama();
                fu.setLocationRelativeTo(null);
                fu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackupRestore;
    private javax.swing.JButton btnCariTkonsumen;
    private javax.swing.JButton btnCariTreseller;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPakaian;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReportTR;
    private javax.swing.JButton btnReportTransaksiKonsumen;
    private javax.swing.JButton btnReseller;
    private javax.swing.JButton btnTransKonsumen;
    private javax.swing.JButton btnTransReseller;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField fieldCariTKonsumen;
    private javax.swing.JTextField fieldCariTReseller;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioOperator;
    private javax.swing.JTable tableTransKonsumen;
    private javax.swing.JTable tableTransReseller;
    // End of variables declaration//GEN-END:variables
}
